theme: jekyll-theme-slate
<div id="observablehq-345fc342"></div>
<script type="module">
import {Runtime, Inspector} from "https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js";
import define from "https://api.observablehq.com/@d3/smooth-zooming.js?v=3";
const inspect = Inspector.into("#observablehq-345fc342");
(new Runtime).module(define, name => (name === "chart") && inspect());
</script>
title: <font color="#c5f015"> Towards data driven investing </font>
description: <font color="#c5f015"> Artificial Intelligence powered equity protfolios </font>
